#define		INCHES_PER_CENTIMETER	0.394
#define		CENTIMETERES_PER_INCH	1 / INCHES_PER_CENTIMETER

#define		QUARTS_PER_LITER		1.057
#define		LITERS_PER_QUART		1 / QUARTS_PER_LITER

#define		OUCES_PER_GRAM			0.035
#define		GRAMS_PER_OUNCE			1 / OUCES_PER_GRAM
